// https://www.goodhousekeeping.com/health/wellness/g2401/inspirational-quotes/?utm_source=google&utm_medium=cpc&utm_campaign=mgu_ga_ghk_md_pmx_hybd_mix_ca_20310565167&gad_source=1&gbraid=0AAAAADA2MEqA44N6ERSXklu2AyvvndtH_&gclid=Cj0KCQjwh_i_BhCzARIsANimeoHxX3Ulu9orGWMX4Q8glRiDTexGRQaS4fZiS6ymBkzZqEvBpJkaeboaAnnyEALw_wcB

export const QUOTES: string[] = [
    "If I cannot do great things, I can do small things in a great way. —Martin Luther King, Jr.",
    "Act as if what you do makes a difference. It does. —William James",
    "Be the change that you wish to see in the world. —Mahatma Ghandi",
    "Don't sit down and wait for the opportunities to come. Get up and make them. —Madam C.J. Walker",
    "Opportunity is missed by most people because it is dressed in overalls and looks like work. —Thomas Edison",
    "The most difficult thing is the decision to act; the rest is merely tenacity. —Amelia Earhart",
    "The bad news is time flies. The good news is you're the pilot. —Michael Altshuler",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. —Jimmy Dean",
    "You get what you give. —Jennifer Lopez",
    "It is often the small steps, not the giant leaps, that bring about the most lasting change. —Queen Elizabeth II",
    "If what you have done yesterday still looks big to you, you haven't done much today. —Mikhail Gorbachev",
    "In the long run, you make your own luck — good, bad, or indifferent. —Loretta Lynn",
    "If my mind can conceive it, if my heart can believe it, then I can achieve it. —Muhammad Ali",
    "Believe you can and you're halfway there. —Theodore Roosevelt",
    "Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination. —Mae Jemison",
    "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. —Marie Curie",
    "The people who are crazy enough to think they can change the world are the ones who do. —Steve Jobs",
    "I scorched the earth with my talent and I let my light shine. —André Leon Talley",
    "Nothing is impossible. The word itself says 'I'm possible!' —Audrey Hepburn",
    "Never bend your head. Always hold it high. Look the world straight in the eye. —Helen Keller",
    "Never allow a person to tell you no who doesn’t have the power to say yes. —Eleanor Roosevelt",
    "It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent. —Madeleine Albright",
    "You are never too old to set another goal or to dream a new dream. —C.S. Lewis",
    "When you have a dream, you've got to grab it and never let go. —Carol Burnett",
    "Let us make our future now, and let us make our dreams tomorrow's reality. —Malala Yousafzai",
    "All our dreams can come true — if we have the courage to pursue them. —Walt Disney",
    "Go confidently in the direction of your dreams. Live the life you have imagined. —Henry David Thoreau",
    "All dreams are within reach. All you have to do is keep moving towards them. —Viola Davis",
    "Dreams don’t have to just be dreams. You can make it a reality; if you just keep pushing and keep trying, then eventually you’ll reach your goal. —Naomi Osaka",
    "Shoot for the moon. Even if you miss, you'll land among the stars. —Norman Vincent Peale",
    "There is nothing impossible to they who will try. —Alexander the Great",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. —Winston Churchill",
    "Champions keep playing until they get it right. —Billie Jean King",
    "We will fail when we fail to try. —Rosa Parks",
    "A person who never made a mistake never tried anything new. —Albert Einstein",
    "Challenges are gifts that force us to search for a new center of gravity. Don't fight them. Just find a new way to stand. —Oprah Winfrey",
    "It ain’t about how hard you hit. It’s about how hard you can get hit and keep moving forward. —Sylvester Stallone",
    "Our predecessors overcame many troubles and much suffering, but each time got back up stronger than before. —Shinzo Abe",
    "I have learned not to allow rejection to move me. —Cicely Tyson",
    "Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong. —Ella Fitzgerald",
    "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome. —William James",
    "Attitude is the 'little' thing that makes a big difference. —Winston Churchill",
    "Once you replace negative thoughts with positive ones, you'll start having positive results. —Willie Nelson",
    "If you’re not positive energy, you’re negative energy. —Mark Cuban",
    "Inspiration comes from within yourself. One has to be positive. When you're positive, good things happen. —Deep Roy",
    "Optimism is a happiness magnet. If you stay positive, good things and good people will be drawn to you. —Mary Lou Retton",
    "I don't harp on the negative because if you do, then there's no progression. There's no forward movement. You got to always look on the bright side of things, and we are in control. —Taraji P. Henson",
    "I know not all that may be coming, but be it what it will, I'll go to it laughing. —Herman Melville",
    "Where there's hope, there's life. It fills us with fresh courage and makes us strong again. —Anne Frank",
    "Once you face your fear, nothing is ever as hard as you think. —Olivia Newton-John",
    "You’re braver than you believe, stronger than you seem, and smarter than you think. —A.A. Milne",
    "You must do the things you think you cannot do. —Eleanor Roosevelt",
    "The Sun himself is weak when he first rises, and gathers strength and courage as the day gets on. —Charles Dickens",
    "When your dreams are bigger than the places you find yourself in, sometimes you need to seek out your own reminders that there is more. And there is always more waiting for you on the other side of fear. —Elaine Welteroth",
    "Happiness is not something readymade; it comes from your own actions. —The Dalai Lama",
    "You do not find the happy life. You make it. —Camilla Eyring Kimball",
    "Happiness is not by chance, but by choice. —Jim Rohn",
    "Happiness often sneaks in through a door you didn't know you left open. —John Barrymore",
    "The miracle is not that we do this work, but that we are happy to do it. —Mother Theresa",
    "Some people look for a beautiful place. Others make a place beautiful. —Hazrat Inayat Khan",
    "Stay close to anything that makes you glad you are alive. —Hafez",
    "For one to have complete satisfaction from flowers, you must have time to spend with them. —Grace Kelly",
    "Always work hard and have fun in what you do because I think that's when you're more successful. You have to choose to do it. —Simone Biles",
    "I never dreamed about success. I worked for it. —Esteé Lauder",
    "Failure is the condiment that gives success its flavor. —Truman Capote",
    "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. —Bob Dylan",
    "The best revenge is massive success. —Frank Sinatra",
    "Try to be a rainbow in someone else's cloud. —Maya Angelou",
    "If you want to lift yourself up, lift up someone else. —Booker T. Washington",
    "We can't help everyone, but everyone can help someone. —Ronald Reagan",
    "It has always been easy to hate and destroy. To build and to cherish is much more difficult. —Queen Elizabeth II",
    "You can't rely on how you look to sustain you, what sustains us, what is fundamentally beautiful is compassion; for yourself and your those around you. —Lupita Nyong'o",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. —Albert Einstein",
    "It’s no use going back to yesterday because I was a different person then. —Lewis Caroll",
    "It isn't where you came from. It's where you're going that counts. —Ella Fitzgerald",
    "Tough times never last, but tough people do. —Robert H. Schuller",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals. —Michelle Obama",
    "You define your own life. Don’t let other people write your script. —Oprah Winfrey",
    "You make a choice: continue living your life feeling muddled in this abyss of self-misunderstanding, or you find your identity independent of it. You draw your own box. —Meghan Markle",
    "It is never too late to be what you might have been. —George Eliot",
    "I always wanted to be somebody, but now I realize I should have been more specific. —Lily Tomlin"
];
  